<?php
$activeEnchereListe = $this->activeEnchereListe; /* @var $activeEnchereListe EnchereSearch */
$this->activeEnchereListe = $activeEnchereListe;
?>


ACCUEIL GUEST
<br>
-------------------------
<br>

<a href="<?=$this->url(array(),'user_addaccount')?>">Créer un compte</a>
<br>
<a href="<?=$this->url(array(),'login')?>">Se connecter</a>
<br><br>

<?php echo $this->render('index/partials/enchere_liste.phtml');?>

<?php
// test mail
$mail = new App_Mail("FRONTEND.ALERTE.COMMON");
$mail->AddAddress('celine.roux@rcweb.io');
$mail->content = 'ceci est un email de test executive project from localhost';
$mail->subject = 'mail de test localhost ep';
$sent = true;
try {
	$mail->send();
	print 'mail send ';
} catch (Exception $e){
	$sent = false;
	print 'failed: '.$e->getMessage();
}

?>